jobs:
- job: FormatValidation
  displayName: Format Validation
  pool:
    vmImage: ubuntu-20.04

  steps:
  - checkout: self
    submodules: true

  - script: curl https://raw.githubusercontent.com/Sarcasm/run-clang-format/master/run-clang-format.py --output run-clang-format.py
    displayName: Download run-clang-format.py

  - script: python ./run-clang-format.py -r include tests benchmarks --style file
    displayName: Validate

- job: Build
  strategy:
    matrix:
      'Ubuntu 20.04':
        os: ubuntu-20.04
        CC: 'gcc-10'
        CXX: 'g++-10'
  pool:
    vmImage: $(os)

  variables:
    CC: $(CC)
    CXX: $(CXX)
  
  steps:
  - checkout: self
    submodules: true

  - task: Cache@2
    displayName: Cache vcpkg
    inputs:
      key: $(Build.SourcesDirectory)/vcpkg-dependencies.txt | "$(Build.SourcesDirectory)/.git/modules/vcpkg/HEAD" | "$(Agent.OS)"
      path: '$(Build.SourcesDirectory)/vcpkg'

  - task: run-vcpkg@0
    displayName: Run vcpkg
    inputs:
      vcpkgArguments: '@$(Build.SourcesDirectory)/vcpkg-dependencies.txt'
      vcpkgDirectory: $(Build.SourcesDirectory)/vcpkg

  - task: run-cmake@0
    displayName: Configure and Build
    inputs:
      cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
      useVcpkgToolchainFile: true
      cmakeAppendedArgs: -G Ninja -DMATRIXPP_BUILD_TESTS=TRUE -DMATRIXPP_BUILD_BENCHMARKS=TRUE
