trigger:
  branches:
    include:
    - master
    - /*

name: Formatting
displayName: 'Formatting'
jobs:
  - job: ClangFormatValidation
    displayName: 'Clang Format Validation'
    steps:
    - checkout: self
    - bash: echo Hello