name: CI

jobs:
  - job: FormatValidation
    displayName: Format Validation
    pool:
      vmImage: ubuntu-20.04

    steps:
      - checkout: self

      - script: |
          git clone https://github.com/Sarcasm/run-clang-format
        displayName: Clone run-clang-format

      - script: |
          sudo apt-get update
          sudo apt-get install clang-format-11
        displayName: Install Clang-Format 11

      - script: python ./run-clang-format/run-clang-format.py -r include external/tests external/include --style file --clang-format-executable=clang-format-11
        displayName: Validate

  - job: UbuntuGCC
    displayName: Ubuntu GCC 10

    pool:
      vmImage: ubuntu-20.04

    steps:
      - checkout: self

      # @TODO: Don't install release candidate once LLVM 12 officially releases
      - script: |
          pip3 install lit==12.0.0rc1 --no-warn-script-location
          echo '##vso[task.prependpath]$(HOME)/.local/bin'
        displayName: Install Python LLVM Lit

      - script: |
          sudo apt-get update
          sudo apt-get install gcovr
        displayName: Install GCC Gcovr

      - script: |
          cmake -DMPP_BUILD_TESTS=TRUE -DMPP_CODE_COVERAGE=TRUE -DCMAKE_CXX_COMPILER=/usr/bin/g++-10 -B build
          cmake --build build --target tests
        displayName: Configure and Build Tests

      - script: |
          cd build/bin/tests
          lit . --xunit-xml-output results.xml
        continueOnError: true # Tests might fail, but we still want the results
        displayName: Run Tests

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: JUnit
          testResultsFiles: "**/results.xml"
        displayName: Publish Tests Results

      - script: cmake --build build --target mpp_code_coverage
        displayName: Generate Code Coverage

      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: cobertura
          summaryFileLocation: build/mpp_code_coverage.xml
          pathToSources: $(Build.SourcesDirectory)
        displayName: Publish Code Coverage

  - job: UbuntuClang
    displayName: Ubuntu Clang 11

    pool:
      vmImage: ubuntu-20.04

    steps:
      - checkout: self

      # @TODO: Don't install release candidate once LLVM 12 officially releases
      - script: |
          pip3 install lit==12.0.0rc1 --no-warn-script-location
          echo '##vso[task.prependpath]$(HOME)/.local/bin'
        displayName: Install Python LLVM Lit

      - script: |
          sudo apt-get update
          sudo apt-get install clang-11 clang++-11
        displayName: Install Clang 11

      - script: |
          cmake -DMPP_BUILD_TESTS=TRUE -DCMAKE_CXX_COMPILER=/usr/bin/clang++-11 -B build
          cmake --build build --target tests
        displayName: Configure and Build Tests

      - script: |
          cd build/bin/tests
          lit . --xunit-xml-output results.xml
        continueOnError: true # Tests might fail, but we still want the results
        displayName: Run Tests

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: JUnit
          testResultsFiles: "**/results.xml"
        displayName: Publish Tests Results

  - job: WindowsMSVC
    displayName: Windows MSVC 19.28 (VS 16.9.0)

    pool:
      vmImage: windows-latest

    steps:
      - checkout: self

      # @TODO: Don't install release candidate once LLVM 12 officially releases
      - script: |
          pip install lit==12.0.0rc1 --no-warn-script-location
          echo '##vso[task.prependpath]$(HOME)/.local/bin'
        displayName: Install Python LLVM Lit

      - script: |
          call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

          cmake -DMPP_BUILD_TESTS=TRUE -DCMAKE_CXX_COMPILER=cl -B build
          cmake --build build --target tests
        displayName: Configure and Build Tests

      - script: |
          cd build/bin/tests
          lit . --xunit-xml-output results.xml
        continueOnError: true # Tests might fail, but we still want the results
        displayName: Run Tests

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: JUnit
          testResultsFiles: "**/results.xml"
        displayName: Publish Tests Results

  - job: WindowsClang
    displayName: Windows Clang 11

    pool:
      vmImage: windows-latest

    steps:
      - checkout: self

      # @TODO: Don't install release candidate once LLVM 12 officially releases
      - script: |
          pip install lit==12.0.0rc1 --no-warn-script-location
          echo '##vso[task.prependpath]$(HOME)/.local/bin'
        displayName: Install Python LLVM Lit

      - script: |
          call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

          cmake -DMPP_BUILD_TESTS=TRUE -DCMAKE_CXX_COMPILER=clang-cl -G Ninja -B build
          cmake --build build --target tests
        displayName: Configure and Build Tests

      - script: |
          cd build/bin/tests
          lit . --xunit-xml-output results.xml
        continueOnError: true # Tests might fail, but we still want the results
        displayName: Run Tests

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: JUnit
          testResultsFiles: "**/results.xml"
        displayName: Publish Tests Results
