name: Format

on: push

jobs:
  Validate:
    runs-on: ubuntu-20.04

    steps:  
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - uses: mstachniuk/ci-skip@v1
        with:
          fail-fast: true

      - name: Checkout run-clang-format
        run: git clone https://github.com/Sarcasm/run-clang-format

      - name: Validate
        run: python ./run-clang-format/run-clang-format.py -r include test --style file
