name: GitHub Pages
on:
  push:
    branches:
      - gh-pages

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install
        run: npm install
      
      - name: Build
        run: npm run build

      - name: Set Git Credentials
        run: |
          git config user.email "samestimable2016@gmail.com"
          git config user.name "Sam Huang"

      - name: Deploy
        run: npm run deploy