name: Linux

on: push

jobs:
  Build:
    runs-on: ubuntu-20.04

    steps:
      - uses: mstachniuk/ci-skip@v1
        with:
          fail-fast: true
          exit-code: 0
      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v6
        with:
          vcpkgArguments: '@${{ github.workspace }}/vcpkg-dependencies.txt'
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          appendedCacheKey: ${{ hashFiles( '${{ github.workspace}}/vcpkg-dependencies.txt' ) }}

      - name: Install GCC 10
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt install gcc-10 g++-10
          
      - name: Build
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: 'CMakeListsTxtAdvanced'
          buildDirectory: '${{ github.workspace }}/build'
          cmakeAppendedArgs: '-DMATRIXPP_BUILD_TEST=TRUE -DCMAKE_BUILD_TYPE=Release'
        env:
          CC: /usr/bin/gcc-10
          CXX: /usr/bin/g++-10

      - name: Set Build Status
        id: build_status
        run: echo ::set-output name=exit_status::success

      - name: Install Python Lit
        run: |
          pip install lit
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run Unit and Compile Test
        run: |
          cd '${{ github.workspace }}/build/bin/test'
          lit compile_test unit_test --xunit-xml-output results.xml
        env:
          CC: /usr/bin/gcc-10
          CXX: /usr/bin/g++-10

      - name: Publish Unit and Compile Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.5
        with:
          files: '**/results.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
        if: steps.build_status.outputs.exit_status == 'success'

      - name: Run Performance Test
        run: |
          cd '${{ github.workspace }}/build/bin/test/performance_test'
          ./all_tests --benchmark_format=json | tee results.json

      - name: Publish Benchmark Results
        uses: rhysd/github-action-benchmark@v1
        with:
          tool: 'googlecpp'
          output-file-path: '${{ github.workspace }}/build/bin/test/performance_test/results.json'
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          auto-push: true
