name: Linux

on: push

jobs:
  Build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: '0'

      - uses: mstachniuk/ci-skip@v1
        with:
          fail-fast: true
      
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v6
        with:
          vcpkgArguments: '@${{ github.workspace }}/vcpkg-dependencies.txt'
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          appendedCacheKey: ${{ hashFiles( '${{ github.workspace}}/vcpkg-dependencies.txt' ) }}

      - name: Install GCC 10
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt install gcc-10 g++-10
          
      - name: Build
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: 'CMakeListsTxtAdvanced'
          buildDirectory: '${{ github.workspace }}/build'
          cmakeAppendedArgs: '-DMATRIXPP_BUILD_TEST=TRUE -DCMAKE_BUILD_TYPE=Release'
        env:
          CC: /usr/bin/gcc-10
          CXX: /usr/bin/g++-10
