name: Performance Test

on:
  workflow_run:
    workflows: ['Linux']
    branches: [main]
    types: 
      - completed

jobs:
  Report:
    runs-on: ubuntu-20.04

    steps:
      - name: Benchmark
        run: |
          cd '${{ github.workspace }}/build/bin/test/performance_test'
          ./all_tests --benchmark_format=json | tee results.json

      - name: Publish Benchmark Results
        uses: rhysd/github-action-benchmark@v1
        with:
          tool: 'googlecpp'
          output-file-path: '${{ github.workspace }}/build/bin/test/performance_test/results.json'
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          auto-push: true
