name: Unit Test

on:
  workflow_run:
    workflows: ['Linux']
    types: 
      - completed
      - requested

jobs:
  Report:
    runs-on: ubuntu-20.04

    steps:
      - name: Install Python Lit
        run: |
          pip install lit
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Test
        run: |
          cd '${{ github.workspace }}/build/bin/test'
          lit compile_test unit_test --xunit-xml-output results.xml
        env:
          CC: /usr/bin/gcc-10
          CXX: /usr/bin/g++-10

      - name: Publish Unit and Compile Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.5
        with:
          files: '**/results.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
        if: steps.build_status.outputs.exit_status == 'success'
